from repositories.bovinoRepository import BovinoRepository
from repositories.pesajeRepository import PesajeRepository
from repositories.estadoAnimalRepository import EstadoAnimalRepository
from repositories.loteRepository import LoteRepository
from repositories.potreroRepository import PotreroRepository