from models.medicamento import Medicamento
from models.tipoAlimento import TipoAlimento
from models.potrero import Potrero,EstadoPotrero
from models.lote import Lote,TipoLote
from models.bovino import Bovino,RazaBovinos,SexoBovinos,OrigenBovino
from models.pesaje import Pesaje
from models.vacunacion import Vacunacion
from models.estadoAnimal import EstadoAnimal,Estado
from models.alimentacion import Alimentacion
